#! python


def build(ctx):
    ctx.recurse("data_management")
    ctx.recurse("analysis")
    ctx.recurse("final")
    # Safety measure -- else the LaTeX scanner might fail because some
    # '.tex'-source file has not been generated.
    ctx.add_group()
    ctx.recurse("paper")
{% if cookiecutter.configure_running_sphinx_from_waf == "y" %}    ctx.recurse("documentation"){% endif %}
