[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]


[tool.setuptools_scm]
write_to = "src/{{ cookiecutter.project_slug }}/_version.py"

[tool.pytask.ini_options]
paths = ["./src/{{ cookiecutter.project_slug }}", "./paper"]
{% if cookiecutter.is_ci == "no" %}
infer_latex_dependencies = true
{% endif %}
