#! python


import os

from collections import OrderedDict

# The project root directory and the build directory.
top = "."
out = "bld"


def set_project_paths(ctx):
    """Return a dictionary with project paths represented by Waf nodes."""

    pp = OrderedDict()
    pp["PROJECT_ROOT"] = "."
    pp["IN_DATA_EXTERNAL"] = "src/data/external"
    pp["IN_DATA_PROCESSED"] = "src/data/processed"
    pp["IN_DATA_RAW"] = "src/data/raw"
    pp["IN_MODEL_CODE"] = "src/model_code"
    pp["IN_MODEL_SPECS"] = "src/model_specs"
    pp["IN_FIGURES"] = "src/figures"
    pp["BLD"] = ""
    pp["OUT_DATA"] = f"{out}/out/data"
    pp["OUT_ANALYSIS"] = f"{out}/out/analysis"
    pp["OUT_FINAL"] = f"{out}/out/final"
    pp["OUT_FIGURES"] = f"{out}/out/figures"
    pp["OUT_TABLES"] = f"{out}/out/tables"

    # Convert the directories into Waf nodes.
    for key, val in pp.items():
        pp[key] = ctx.path.make_node(val)

    return pp


def path_to(ctx, pp_key, *args):
    """Return the relative path to os.path.join(*args*) in the directory
    PROJECT_PATHS[pp_key] as seen from ctx.path (i.e. the directory of the
    current wscript).

    Use this to get the relative path---as needed by Waf---to a file in one
    of the directory trees defined in the PROJECT_PATHS dictionary above.

    We always pretend everything is in the source directory tree, Waf takes
    care of the correct placing of targets and sources.

    """

    # Implementation detail:
    #   We find the path to the directory where the file lives, so that
    #   we do not accidentally declare a node that does not exist.
    dir_path_in_tree = os.path.join(".", *args[:-1])
    # Find/declare the directory node. Use an alias to shorten the line.
    pp_key_fod = ctx.env.PROJECT_PATHS[pp_key].find_or_declare
    dir_node = pp_key_fod(dir_path_in_tree).get_src()
    # Get the relative path to the directory.
    path_to_dir = dir_node.path_from(ctx.path)
    # Return the relative path to the file.
    return os.path.join(path_to_dir, args[-1])


def configure(ctx):
    ctx.env.PYTHONPATH = os.getcwd()
    # Disable on a machine where security risks could arise
    ctx.env.PDFLATEXFLAGS = "-shell-escape"

    {% if cookiecutter.configure_running_python_from_waf == "y" %}ctx.load("run_py_script"){% endif %}
    {% if cookiecutter.configure_running_stata_from_waf == "y" %}ctx.load("run_do_script"){% endif %}
    {% if cookiecutter.configure_running_matlab_from_waf == "y" %}ctx.load("run_m_script") {% endif %}
    {% if cookiecutter.configure_running_r_from_waf == "y" %}ctx.load("run_r_script") {% endif %}
    {% if cookiecutter.configure_running_julia_from_waf == "y" %}ctx.load("run_jl_script") {% endif %}
    {% if cookiecutter.configure_running_sphinx_from_waf == "y" %}ctx.load("sphinx_build"){% endif %}
    {% if cookiecutter.configure_running_latex_from_waf == "y" %}ctx.load("biber"){% endif %}

    ctx.load("write_project_headers")
    ctx.find_program("dot")


def build(ctx):
    ctx.env.PROJECT_PATHS = set_project_paths(ctx)
    ctx.path_to = path_to
    # Generate header file with project paths in "bld" directory

    {% if cookiecutter.configure_running_python_from_waf == "y" %}ctx(features="write_project_paths", target="project_paths.py") {% endif %}
    {% if cookiecutter.configure_running_stata_from_waf == "y" %}ctx(features="write_project_paths", target="project_paths.do"){% endif %}
    {% if cookiecutter.configure_running_matlab_from_waf == "y" %}ctx(features="write_project_paths", target="project_paths.m"){% endif %}
    {% if cookiecutter.configure_running_r_from_waf == "y" %}ctx(features="write_project_paths", target="project_paths.r"){% endif %}
    {% if cookiecutter.configure_running_julia_from_waf == "y" %}ctx(features="write_project_paths", target="project_paths.py"){% endif %}
    ctx(features='write_project_paths', target='project_paths.py')
    ctx.add_group()
    ctx.recurse("src")
