pr: none

variables:
  CI: true

jobs:
- job:
  displayName: Linux
  pool:
    vmImage: "ubuntu-16.04"
  strategy:
    matrix:
      Python36:
        python.version: "3.6"
      Python37:
        python.version: "3.7"

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH.

  - bash: conda update conda --yes --quiet
    displayName: Update conda.

  - bash: conda create --yes --quiet --name cc -c defaults -c conda-forge python=$PYTHON_VERSION tox
    displayName: Create Anaconda environment.

  - bash: |
      source activate cc
      tox -e pytest
      tox -e sphinx -e linting -p auto
- job:
  displayName: Windows
  pool:
    vmImage: "windows-2019"
  strategy:
    matrix:
      Python36:
        python.version: "3.6"
      Python37:
        python.version: "3.7"

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH.

  - powershell: conda update conda --yes --quiet
    displayName: Update conda.

  - powershell: conda create --yes --quiet --name cc -c defaults -c conda-forge python=$env:PYTHON_VERSION tox
    displayName: Create Anaconda environment.

  - script: |
      call activate cc
      tox -e pytest
- job:
  displayName: MacOS
  pool:
    vmImage: "macOS-10.13"
  strategy:
    matrix:
      Python36:
        python.version: "3.6"
      Python37:
        python.version: "3.7"

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH.

  # On hosted macOS, the agent user doesn't have ownership of Miniconda's installation
  # directory. We need to take ownership if we want to update conda or install packages
  # globally.
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: conda update conda --yes --quiet
    displayName: Update conda.

  - bash: conda info -a

  - bash: conda create --yes --quiet --name cc -c defaults -c conda-forge python=$PYTHON_VERSION tox
    displayName: Create Anaconda environment.

  - bash: conda list

  - bash: |
      source activate cc
      tox -e pytest
