pr: none

jobs:
- job:
  displayName: Linux
  pool:
    vmImage: "ubuntu-16.04"

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH.

  - bash: conda update conda --yes --quiet
    displayName: Update conda.

  - bash: conda env create -n econ-project-templates -f environment.yml
    displayName: Create Anaconda environment.

  - bash: sudo apt-get install git
    displayName: Install git.

  - bash: |
      git config --global user.name "John Doe"
      git config --global user.email johndoe@example.com
    displayName: Configure git.

  - bash: |
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get install texlive-base
    displayName: Install Latex.

  - bash: |
      source activate econ-project-templates
      pytest
    displayName: Run pytests.

  - bash: |
      source activate econ-project-templates
      cd docs
      python waf.py configure build install
    displayName: Compile Docs.


- job:
  displayName: MacOS
  pool:
    vmImage: "macOS-10.13"

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH.

  # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation
  # directory. We need to take ownership if we want to update conda or install packages
  # globally.
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: conda update conda --yes --quiet
    displayName: Update conda.

  - bash: conda env create -n econ-project-templates -f environment.yml
    displayName: Create Anaconda environment.

  - bash: brew install git
    displayName: Install git.

  - bash: |
      git config --global user.name "John Doe"
      git config --global user.email johndoe@example.com
    displayName: Configure git.

  - bash: |
      brew install caskroom/cask/brew-cask
      brew cask install mactex
    displayName: Install Latex.

  - bash: |
      source activate econ-project-templates
      pytest
    displayName: Run pytests.

  - bash: |
      source activate econ-project-templates
      cd docs
      python waf.py configure build install
    displayName: Compile Docs.
