language: python
python:
  - "3.6"
  - "3.7"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION jupyterlab=0.32 pandas=0.23 python=3.7 python-graphviz=0.8
  - pip install click==7.0 isort==4.3.4 black==18.9b0 matplotlib==3 nbsphinx==0.3 pytest==3.8 pytest-cov==2.5 pytest-pythonpath==0.7 pytest-cookies sphinx==1.7.6 sphinx-autobuild==0.7.1 sphinx-rtd-theme==0.4.1 sphinxcontrib-bibtex==0.4 sphinxcontrib-matlabdomain==0.5.0


  - source activate test-environment
  # - python setup.py install

script:
  - pytest