name: econ-project-templates
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pip:
    - cookiecutter
    - nbsphinx
    - pre-commit
    - pytest
    - pytest-cookies
    - pytest-cov
    - pytest-pythonpath
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
