name: econ-project-templates

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip>=21.1
  - setuptools_scm
  - toml
  - mamba

  # Package dependencies
  - cookiecutter
  - pytask>=0.2
  - pytask-latex
  - plotly>=5.5.0
  - pandas
  - ipykernel
  - jupyterlab

  # Documentation
  - furo
  - black
  - ipython
  - ipython_genutils
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-panels
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme>=0.3.0
  - myst-parser
  - python-kaleido

  # Misc
  - black
  - ipython
  - pre-commit
  - pytest
  - pytest-cov
  - tox-conda
  - pip: # pytest-cookiecutter
    - tox-current-env
    - git+https://github.com/andriihomiak/pytest-cookies.git@fix/quotes_in_user_config
