---
name: example_project
channels: [conda-forge, r, nodefaults]
dependencies:
  - python=3.12
  - r-plyr
  - conda-lock
  - ipykernel
  - jupyterlab
  - pandas
  - phantomjs
  - pip >=21.1
  - plotly>=5.13.0
  - pre-commit
  - pytask-r
  - pytask-julia
  - pytask-latex>=0.4.0
  - pytask-parallel>=0.4.0
  - pytask-stata
  - pytask>=0.4.0
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz
  - pyyaml
  - plotly-orca
  - r-plotly
  - r-processx
  - r-reshape2
  - r-reticulate
  - r-webshot
  - r-xtable
  - setuptools_scm
  - statsmodels
  - toml
  - pip: [-e ., kaleido, pdbp]
