name: econ-project-templates
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - pip
  - pandas
  - python=3.7
  - python-graphviz
  - pip:
    - click==7.0
    - cookiecutter
    - nbsphinx
    - pre-commit
    - pytest
    - pytest-cookies
    - pytest-cov
    - pytest-pythonpath
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
