name: econ-project-templates
channels:
  - defaults
  - r
  - conda-forge
dependencies:
  - matplotlib
  - pip
  - pandas
  - python=3.7
  - python-graphviz
  - pip:
    - click==7.0
    - cookiecutter
    - nbsphinx
    - pre-commit
    - pytest
    - pytest-cookies
    - pytest-cov
    - pytest-pythonpath
    - r-aer
    - r-aod
    - r-base
    - r-car
    - r-essentials
    - r-rjson
    - r-lmtest
    - r-sandwich
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
