name: econ-project-templates
channels:
  - conda-forge
  - r
  - plotly
dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - plotly>=5.5.0
  - pandas
  - pip
  - pytask>=0.0.14
  - pytask-latex>=0.0.12
  - pytask-r>=0.0.9
  - pytask-stata>=0.0.6
  - pytest
  - pytest-cov
  - python=3.9
  - python-graphviz
  - tox-conda
  - r-aer
  - r-aod
  - r-base
  - r-car
  - r-essentials
  - r-rjson
  - r-lmtest
  - r-sandwich
  - pip:
    - click==7.0
    - cookiecutter
    - kaleido
    - nbsphinx
    - pre-commit
    - pytest-cookies
    - pytest-pythonpath
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
