---
name: template_project
channels: [conda-forge, r, nodefaults]
dependencies:
  - python ==3.12
  - pip >=21.1

  # Development dependencies
  - conda-lock
  - ipykernel
  - jupyterlab
  - pre-commit

  # Language agnostic template project dependencies
  - pytask >=0.5.0
  - pytask-latex >=0.4.2
  - pytask-parallel >=0.5.0
  - pytest
  - pytest-cov
  - pytest-xdist

  # Python template project dependencies
  - statsmodels
  - numpy
  - pandas >=2.2
  - plotly >=5.2.0,<6

  # R template project dependencies
  - pytask-r >=0.4.1
  - pyreadr
  - r-plyr
  - r-precommit
  - r-yaml
  - r-forcats

  # Install project
  - pip: [-e ., pdbp, kaleido]
