---
name: econ-project-templates

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - mamba
  - conda=22.9
  - pip>=22.3
  - setuptools_scm
  - toml

  # Package dependencies
  - cookiecutter
  - pytask>=0.2
  - pandas
  - ipykernel
  - jupyterlab
  - plotly>=5.5.0
  - python-kaleido

  # Documentation
  - furo
  - black
  - ipython
  - ipython_genutils
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-panels
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme>=0.3.0
  - myst-parser

  # Misc
  - pdbpp
  - pre-commit
  - pytest
  - pytest-cov
  - pip:
      - git+https://github.com/andriihomiak/pytest-cookies.git@fix/quotes_in_user_config
