name: cp

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.8
  - pip >=21.1
  - setuptools_scm
  - toml

  # Package dependencies
  - cookiecutter
  - pytask >=0.1.9

  # Misc
  - black
  - ipython
  - mypy
  - pre-commit
  - pytest
  - pytest-cookies
  - pytest-cov
  - pytest-xdist
  - tox-conda

  # Documentation
  - furo
  - black
  - ipython
  - ipython_genutils
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-panels
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme>=0.3.0
