name: econ-project-templates
channels:
  - defaults
  - r
  - conda-forge
  - pytask
dependencies:
  - matplotlib
  - pip
  - pandas
  - python=3.7
  - python-graphviz=0.8
  - pytask>=0.0.11
  - pytask-latex>=0.0.9
  - r-aer
  - r-aod
  - r-base
  - r-car
  - r-essentials
  - r-rjson
  - r-lmtest
  - r-sandwich
  - pip:
    - click==7.0
    - cookiecutter
    - nbsphinx
    - pre-commit
    - pytest
    - pytest-cookies
    - pytest-cov
    - pytest-pythonpath
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
