name: example_project
channels:
  - defaults
dependencies:
  - jupyterlab=0.32
  - pandas=0.23
  - python=3.7
  - python-graphviz=0.8
  - pip:
    - click==7.0

    - matplotlib==3
    - nbsphinx==0.3
    - pytest==3.8
    - pytest-cov==2.5
    - pytest-pythonpath==0.7

