#! python


def build(ctx):

    ctx(
        features="subst",
        source=ctx.path_to(ctx, "IN_FIGURES", "matplotlibrc"),
        target=ctx.path_to(ctx, "BLD", "matplotlibrc"),
        is_copy=True,
    )

    for model in "baseline", "max_moves_2":

        ctx(
            features="run_py_script",
            source="plot_locations.py",
            deps=[
                ctx.path_to(ctx, "BLD", "matplotlibrc"),
                ctx.path_to(
                    ctx, "OUT_ANALYSIS", "schelling_{}.pickle".format(model)
                ),
                ctx.path_to(ctx, "IN_MODEL_SPECS", "{}.json".format(model)),
            ],
            target=ctx.path_to(
                ctx, "OUT_FIGURES", "schelling_{}.png".format(model)
            ),
            append=model,
            name="plot_locations_{}".format(model),
        )
