#! python


def build(ctx):

    ctx(
        features="run_r_script",
        source="add_variables.r",
        target=[ctx.path_to(ctx, "OUT_DATA", "ajrcomment_all.csv")],
        deps=[ctx.path_to(ctx, "IN_DATA", "ajrcomment.dta")],
        name="add_variables_r",
    )
