import os


def post_install(ctx):



    install_root = os.path.join(ctx.srcnode.abspath())

    # Now the entire directory tree of the html build, except for hidden stuff.
    html_root = ctx.bldnode.find_node('source/html')
    for n in html_root.ant_glob('*', remove=False, quiet=True):
        rel_path = n.path_from(html_root)
        if not n.name.startswith('.') and not rel_path.startswith('.') and not rel_path.startswith('current'):
            ctx.install_as(os.path.join(install_root, rel_path), n, postpone=False)



def build(ctx):
    # ctx.recurse('devel/python/')
    # ctx.recurse('devel/stata/')
    # ctx.recurse('v1.0/python/')
    # ctx.recurse('v1.0/stata/')
    ctx.recurse('current/python/')
    ctx.recurse('current/stata/')

    ctx(
        features='sphinx',
        builders=['html'],
        source='conf.py'
    )

    ctx.add_post_fun(post_install)