#! python


def build(ctx):
    def out_data(*args):
        return ctx.path_to(ctx, "OUT_DATA", *args)

    def out_analysis(*args):
        return ctx.path_to(ctx, "OUT_ANALYSIS", *args)

    def out_figures(*args):
        return ctx.path_to(ctx, "OUT_FIGURES", *args)

    def out_tables(*args):
        return ctx.path_to(ctx, "OUT_TABLES", *args)

    # Figure 1
    ctx(
        features="run_r_script",
        source="figure_mortality.r",
        target=[out_figures("risk_mort.png"), out_figures("gdp_mort.png")],
        deps=out_data("ajrcomment_all.txt"),
        name="plot_figure.r",
    )

    deps = {"first_stage": [], "second_stage": []}

    models = ["baseline", "rmconj"]

    for m in models:
        for stage, deps_list in deps.items():
            deps_list.append(out_analysis("{}_estimation_{}.txt".format(stage, m)))

    # Table 2
    ctx(
        features="run_r_script",
        source="table_first_stage_est.r",
        target=[out_tables("table_first_stage_est.tex")],
        deps=deps["first_stage"],
        append=" ".join(models),
    )
    # Table 3
    ctx(
        features="run_r_script",
        source="table_second_stage_est.r",
        target=[out_tables("table_second_stage_est.tex")],
        deps=deps["second_stage"],
        append=" ".join(models),
    )

    from src.final.project_dependency_graph import make_project_dependency_graph

    ctx.add_post_fun(make_project_dependency_graph)
