name: python_example_env
channels:
  - conda-forge
  - plotly

  - r

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - plotly>=5.5.0
  - pandas
  - pip
  - pytask<0.2
  - pytask-latex<0.2

  - pytask-r>=0.0.9


  - pytask-stata>=0.0.6

  - pytest
  - pytest-cov
  - python=3.9
  - python-graphviz

  - r-aer
  - r-aod
  - r-base
  - r-car
  - r-essentials
  - r-rjson
  - r-lmtest
  - r-sandwich


  - virtualenv=20.0.33

  - pip:

    - pre-commit

    - kaleido>=0.2.1
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex

    - sphinxcontrib-matlabdomain

