#! python


def build(ctx):

    # More complicated use: Read in the model specifications and run these things
    # in parallel.
    models = ["baseline", "rmconj"]

    for m in models:
        for stage in ["first", "second"]:

            # Run the r-files
            ctx(
                features="run_r_script",
                source=f"{stage}_stage_estimation.r",
                target=[
                    ctx.path_to(
                        ctx,
                        "OUT_ANALYSIS",
                        f"{stage}_stage_estimation_{m}.csv",
                    )
                ],
                deps=[
                    ctx.path_to(ctx, "OUT_DATA", "ajrcomment_all.csv"),
                    ctx.path_to(ctx, "IN_MODEL_CODE", "functions.r"),
                    ctx.path_to(ctx, "IN_MODEL_SPECS", "geography.json"),
                ],
                name=f"{stage}_stage_estimation_{m}",
                append=m,
            )
