def build(ctx):

    model_graphs = [
        'steps_only_full.png',
        'model_steps_full.png',
        'model_steps_part.png',
        'model_steps_select.png'
    ]

    ctx(
        features='run_py_script',
        source='organisation_model_steps.py',
        target=model_graphs
    )
