def build(ctx):

    model_graphs = [
        'steps_only_full.png',
        'model_steps_full.png',
        'model_steps_select.png'
    ]

    ctx(
        features='run_py_script',
        source='organisation_model_steps.py',
        target=model_graphs
    )

    file_trunks = [
        'schelling_dependencies',
        'schelling_dependencies_data_mgmt',
        'schelling_dependencies_main',
        'schelling_dependencies_final',
        'schelling_dependencies_paper'
    ]
    for ft in file_trunks:
        ctx(
            features='tex',
            source='{}.tex'.format(ft),
            outs='pdf png'
        )
