def build(ctx):

    model_graphs = [
        'steps_only_full.png',
        'model_steps_full.png',
        'model_steps_select.png'
    ]

    ctx(
        features='run_py_script',
        source='organisation_model_steps.py',
        target=model_graphs
    )

    project_hierarchies_keys = [
        'big_pic',
        'analysis'
    ]
    project_hierarchies_trunks = []
    for key in project_hierarchies_keys:
        project_hierarchies_trunks.append('project_hierarchies_' + key)
        ctx(
            features='run_py_script',
            source='project_hierarchies.py',
            target='{}.tex'.format(project_hierarchies_trunks[-1]),
            append=key
        )

    ctx.add_group()

    schelling_trunks = [
        'schelling_dependencies',
        'schelling_dependencies_data_mgmt',
        'schelling_dependencies_main',
        'schelling_dependencies_final',
        'schelling_dependencies_paper'
    ]

    for f in schelling_trunks + project_hierarchies_trunks:
        ctx(
            features='tex',
            source='{}.tex'.format(f),
            outs='pdf png'
        )
