name: econ-project-templates-docs
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - pip:
    - nbsphinx
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
