name: econ-project-templates-docs
channels:
  - defaults
  - r
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - pip:
	  - sphinx
	  - sphinx-autobuild
	  - sphinx-rtd-theme
	  - sphinxcontrib-bibtex
