name: econ-project-templates-docs
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - pip
  - python=3.9
  - plotly>=5.5.0
  - pip:
      - kaleido
      - nbsphinx
      - sphinx
      - sphinx-autobuild
      - sphinx-rtd-theme
      - sphinxcontrib-bibtex
