name: econ-project-templates-docs
channels:
  - conda-forge
  - plotly
dependencies:
  - pip
  - python=3.9
  - plotly>=5.5.0
  - python-kaleido>=0.2.1
  - pip:
      - nbsphinx
      - sphinx
      - sphinx-autobuild
      - sphinx-rtd-theme
      - sphinxcontrib-bibtex
