import os


def post_install(ctx):
    # Now the entire directory tree of the html build, except for hidden stuff.
    install_root = os.path.join(ctx.srcnode.abspath())
    html_root = ctx.bldnode.find_node('src/html')
    for n in html_root.ant_glob('**', remove=False, quiet=True):
        rel_path = n.path_from(html_root)
        if not n.name.startswith('.') and not rel_path.startswith('.'):
            ctx.install_as(os.path.join(install_root, rel_path), n, postpone=False)


def build(ctx):
    ctx(
        features='sphinx',
        buildername='html',
        source='conf.py',
        name='sphinx_html'
    )
    # Install only after the build has finished.
    ctx.add_post_fun(post_install)
