#! python


def build(ctx):
    for model in "baseline", "max_moves_2":
        source = "plot_locations"
        ctx(
            features="run_m_script",
            source=f"{source}.m",
            target=ctx.path_to(ctx, "OUT_FIGURES", f"schelling_{model}.png"),
            deps=[
                ctx.path_to(ctx, "OUT_ANALYSIS", f"schelling_{model}.mat"),
                ctx.path_to(ctx, "IN_MODEL_SPECS", f"{model}.json"),
            ],
            append=f"('{model}')",
            name=f"{source}_{model}",
        )

    from src.final.project_dependency_graph import make_project_dependency_graph

    ctx.add_post_fun(make_project_dependency_graph)
