def build(ctx):

    source = 'research_paper'

    ctx(
        features='tex',
        source=source + '.tex',
        prompt=1,
        name=source
    )
    ctx.install_files(
        ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
        source + '.pdf'
    )
