name: main

# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      CONDA_EXE: mamba

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-tinytex@v1
        if: runner.os != 'Windows'
          
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge, nodefaults
            
      - name: Install test dependencies
        shell: bash -l {0}
        run: mamba install pip cookiecutter pytest pytest-cov pytest-xdist
        
      - name: Install pytest-cookies
        shell: bash -l {0}
        run: pip install git+https://github.com/andriihomiak/pytest-cookies.git@fix/quotes_in_user_config
            
      - name: Run tests
        shell: bash -l {0}
        run: pytest tests --cov=hooks --cov=tests --cov-report=xml -n auto
          
      - name: Upload coverage reports
        if: runner.os == 'Linux' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v3


  docs:
    name: Run documentation.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install core dependencies.
        shell: bash -l {0}
        run: conda install -c conda-forge tox-conda

      - name: Build docs
        shell: bash -l {0}
        run: tox -e sphinx
