---
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
conda:
  environment: docs_template/rtd_environment.yml
sphinx:
  builder: html
  configuration: docs_template/source/conf.py
  fail_on_warning: false
